#!/usr/bin/bash
cd /root/RemoteDir/qbot/AronaBot

# export $HOME="/root"

# bash /root/.zshrc

# echo $NVM_DIR/nvm.sh >>0.log

# echo $PATH

/root/.nvm/versions/node/v24.11.0/bin/node /root/.nvm/versions/node/v24.11.0/bin/pnpm run start:$1 >"log/$1_$(date +%F--%H:%M:%S).log" 2>&1 &
