#!/usr/bin/sh
cd /root/RemoteDir/qbot/AronaBot
mkdir /tmp/randPic
/root/.nvm/versions/node/v18.16.1/bin/node node_modules/ts-node/dist/bin.js /root/RemoteDir/qbot/AronaBot/src/index.ts> "log/$(date +%F--%H:%M:%S).log" 2>&1 & 
