export const EventMap = {
    GROUP_AND_C2C_EVENT: [
        IntentEventType.GROUP_ADD_ROBOT,
        IntentEventType.GROUP_AT_MESSAGE_CREATE,
        IntentEventType.GROUP_DEL_ROBOT,
        IntentEventType.GROUP_MSG_RECEIVE,
        IntentEventType.GROUP_MSG_REJECT,
        IntentEventType.C2C_MESSAGE_CREATE,
        IntentEventType.C2C_MSG_RECEIVE,
        IntentEventType.C2C_MSG_REJECT,
        IntentEventType.FRIEND_ADD,
        IntentEventType.FRIEND_DEL,
        IntentEventType.SUBSCRIBE_MESSAGE_STATUS,
    ],
    PUBLIC_GUILD_MESSAGES: [
        IntentEventType.AT_MESSAGE_CREATE,
        IntentEventType.PUBLIC_MESSAGE_DELETE,
    ],
    GUILDS: [
        IntentEventType.GUILD_CREATE,
        IntentEventType.GUILD_DELETE,
        IntentEventType.GUILD_UPDATE,
        IntentEventType.CHANNEL_CREATE,
        IntentEventType.CHANNEL_DELETE,
        IntentEventType.CHANNEL_UPDATE,
    ],
    GUILD_MEMBERS: [
        IntentEventType.GUILD_MEMBER_ADD,
        IntentEventType.GUILD_MEMBER_UPDATE,
        IntentEventType.GUILD_MEMBER_REMOVE,
        IntentEventType.GUILD_MEMBER_REMOVE,
    ],
    GUILD_MESSAGES: [
        IntentEventType.MESSAGE_CREATE,
        IntentEventType.MESSAGE_DELETE,
    ],
    GUILD_MESSAGE_REACTIONS: [
        IntentEventType.MESSAGE_REACTION_ADD,
        IntentEventType.MESSAGE_REACTION_REMOVE,
    ],
    DIRECT_MESSAGE: [
        IntentEventType.DIRECT_MESSAGE_CREATE,
        IntentEventType.DIRECT_MESSAGE_DELETE,
    ],
    MESSAGE_AUDIT: [
        IntentEventType.MESSAGE_AUDIT_PASS,
        IntentEventType.MESSAGE_AUDIT_REJECT,
    ],
    FORUMS_EVENT: [
        IntentEventType.FORUM_THREAD_CREATE,
        IntentEventType.FORUM_THREAD_UPDATE,
        IntentEventType.FORUM_THREAD_DELETE,
        IntentEventType.FORUM_POST_CREATE,
        IntentEventType.FORUM_POST_DELETE,
        IntentEventType.FORUM_REPLY_CREATE,
        IntentEventType.FORUM_REPLY_DELETE,
        IntentEventType.FORUM_PUBLISH_AUDIT_RESULT,
    ],
    OPEN_FORUMS_EVENT: [
        IntentEventType.OPEN_FORUM_THREAD_CREATE,
        IntentEventType.OPEN_FORUM_THREAD_UPDATE,
        IntentEventType.OPEN_FORUM_THREAD_DELETE,
        IntentEventType.OPEN_FORUM_POST_CREATE,
        IntentEventType.OPEN_FORUM_POST_DELETE,
        IntentEventType.OPEN_FORUM_REPLY_CREATE,
        IntentEventType.OPEN_FORUM_REPLY_DELETE,
    ],
    INTERACTION: [IntentEventType.INTERACTION_CREATE],
}