/** 运行时枚举（tsx/esbuild 不支持 .d.ts ambient const enum 内联） */
export enum IntentEventType {
    READY = 'READY',
    MESSAGE_CREATE = 'MESSAGE_CREATE',
    MESSAGE_DELETE = 'MESSAGE_DELETE',
    AT_MESSAGE_CREATE = 'AT_MESSAGE_CREATE',
    PUBLIC_MESSAGE_DELETE = 'PUBLIC_MESSAGE_DELETE',
    DIRECT_MESSAGE_CREATE = 'DIRECT_MESSAGE_CREATE',
    DIRECT_MESSAGE_DELETE = 'DIRECT_MESSAGE_DELETE',
    GUILD_MEMBER_ADD = 'GUILD_MEMBER_ADD',
    GUILD_MEMBER_UPDATE = 'GUILD_MEMBER_UPDATE',
    GUILD_MEMBER_REMOVE = 'GUILD_MEMBER_REMOVE',
    MESSAGE_REACTION_ADD = 'MESSAGE_REACTION_ADD',
    MESSAGE_REACTION_REMOVE = 'MESSAGE_REACTION_REMOVE',
    GUILD_CREATE = 'GUILD_CREATE',
    GUILD_UPDATE = 'GUILD_UPDATE',
    GUILD_DELETE = 'GUILD_DELETE',
    CHANNEL_CREATE = 'CHANNEL_CREATE',
    CHANNEL_UPDATE = 'CHANNEL_UPDATE',
    CHANNEL_DELETE = 'CHANNEL_DELETE',

    FORUM_THREAD_CREATE = 'FORUM_THREAD_CREATE', // 当用户创建主题时
    FORUM_THREAD_UPDATE = 'FORUM_THREAD_UPDATE', // 当用户更新主题时
    FORUM_THREAD_DELETE = 'FORUM_THREAD_DELETE', // 当用户删除主题时
    FORUM_POST_CREATE = 'FORUM_POST_CREATE', // 当用户创建帖子时
    FORUM_POST_DELETE = 'FORUM_POST_DELETE', // 当用户删除帖子时
    FORUM_REPLY_CREATE = 'FORUM_REPLY_CREATE', // 当用户回复评论时
    FORUM_REPLY_DELETE = 'FORUM_REPLY_DELETE', // 当用户删除评论时
    FORUM_PUBLISH_AUDIT_RESULT = 'FORUM_PUBLISH_AUDIT_RESULT', // 当用户发表审核通过时

    OPEN_FORUM_THREAD_CREATE = 'OPEN_FORUM_THREAD_CREATE', // 当用户创建主题时
    OPEN_FORUM_THREAD_UPDATE = 'OPEN_FORUM_THREAD_UPDATE', // 当用户更新主题时
    OPEN_FORUM_THREAD_DELETE = 'OPEN_FORUM_THREAD_DELETE', // 当用户删除主题时
    OPEN_FORUM_POST_CREATE = 'OPEN_FORUM_POST_CREATE', // 当用户创建帖子时
    OPEN_FORUM_POST_DELETE = 'OPEN_FORUM_POST_DELETE', // 当用户删除帖子时
    OPEN_FORUM_REPLY_CREATE = 'OPEN_FORUM_REPLY_CREATE', // 当用户回复评论时
    OPEN_FORUM_REPLY_DELETE = 'OPEN_FORUM_REPLY_DELETE', // 当用户删除评论时

    MESSAGE_AUDIT_PASS = 'MESSAGE_AUDIT_PASS',
    MESSAGE_AUDIT_REJECT = 'MESSAGE_AUDIT_REJECT',

    GROUP_ADD_ROBOT = 'GROUP_ADD_ROBOT',
    GROUP_DEL_ROBOT = 'GROUP_DEL_ROBOT',
    GROUP_MESSAGE_CREATE = 'GROUP_MESSAGE_CREATE',
    GROUP_AT_MESSAGE_CREATE = 'GROUP_AT_MESSAGE_CREATE',
    GROUP_MSG_RECEIVE = 'GROUP_MSG_RECEIVE',
    GROUP_MSG_REJECT = 'GROUP_MSG_REJECT',
    C2C_MESSAGE_CREATE = 'C2C_MESSAGE_CREATE',
    C2C_MSG_RECEIVE = 'C2C_MSG_RECEIVE',
    C2C_MSG_REJECT = 'C2C_MSG_REJECT',
    FRIEND_ADD = 'FRIEND_ADD',
    FRIEND_DEL = 'FRIEND_DEL',

    INTERACTION_CREATE = 'INTERACTION_CREATE',
    SUBSCRIBE_MESSAGE_STATUS = 'SUBSCRIBE_MESSAGE_STATUS',
}
